kunalshetye/opti-astro

- .prettierignore
- .prettierrc.mjs
- package.json
Add prettier + configuration to project
Once other changes are merged, next step with this would be to format project files via the command below, and then commit those changes for a new solution baseline:
_yarn prettier . --write_
> Code formatting with prettier

- src/components/cms/VisualBuilder/components/_Component.astro
- src/layouts/ComponentPreviewLayout.astro
- src/pages/preview.astro
- src/services/graphql/__generated/graphql.schema.graphql
- src/services/graphql/__generated/graphql.schema.json
- src/services/graphql/__generated/sdk.ts
- src/services/graphql/queries/componentById.graphql
Let me know if you have any feedback; should be ready to go in my testing, but please verify against your CMS instance/content.
> Enable preview for standalone shared blocks/components

- src/cms/compositions/Column/Column.astro
This change enables the component alignment styles
Primarily verified against Text component (to enable "Text align" setting), plus additional basic testing
> Set each component parent to full width within column

- utils/styles/push.mjs
Please validate on a non-Windows system
via: https://www.npmjs.com/package/fast-glob#convertpathtopatternpath
> Fix for pushing styles on Windows

- src/cms/components/ArticleList/ArticleList.astro
Wrap cards to multiple lines
Align buttons on cards
Align images on cards
Note: may want to switch to grid + grid styles in the future?
> Article list display update

- src/cms/components/ArticleList/ArticleList.astro
- src/graphql/queries/pages/getArticles.graphql
@kunalshetye I did some initial testing on a quickly-configured multisite instance, but please test against yours since it's more built out.
> Update ArticleList component to only show articles for current site

- src/pages/404.astro
- src/pages/[...page].astro
Phase 1: hardcoded 404 page contents
Future phase/TODO: pull 404 page contents from CMS
> Implement 404 page (hardcoded)

- .gitignore
- .yarnrc.yml
- codegen.ts
- yarn.lock
Updated yarn settings
Updated method to get env settings in graphql codgen
yarn dedupe
Updated gitigrnore for vercel deployments
Fixes local issues + VS Code warnings/errors, and Netlify deploy
(Re-write of original PR https://github.com/kunalshetye/opti-astro/pull/42 )
> Update to fix running locally + VS Code errors

- package.json
- src/cms/components/VideoComponent/Video.astro
- src/cms/components/VideoComponent/video.graphql
- src/cms/components/VideoExternalComponent/VideoExternal.astro
- src/cms/components/VideoExternalComponent/VideoExternal.graphql
- src/cms/components/_Components.astro
- src/cms/components/allComponents.graphql
- yarn.lock
Added poster image option to video component
Added new component for YouTube/Vimeo players
> Add external video player component, update video component

- src/cms/components/ArticleListComponent/ArticleList.astro
- src/cms/components/_Components.astro
- src/cms/pages/ArticlePage/ArticlePageCard.astro
- src/cms/pages/LandingPage/LandingPage.astro
- src/cms/shared/ContentArea/contentArea.graphql
Add ability to drag + drop Article pages into content areas, to display as cards
Update content area rendering
> Update content area rendering and use Articles as cards

- .env.template
- README.md
- astro.config.mjs
- src/cms/shared/DevTools.astro
- src/cms/shared/Footer.astro
- src/cms/shared/devtools/DevToolsPanel.astro
- src/cms/shared/devtools/EnvironmentPanel.astro
- src/cms/shared/devtools/GraphQLPanel.astro
- src/cms/shared/devtools/PerformancePanel.astro
- src/cms/shared/utils.ts
- src/graphql/getSdk.ts
> added extensible developer tools

- src/cms/compositions/Column/ColumnHelper.ts
- src/cms/compositions/Column/DefaultColumn.opti-style.json
- src/cms/compositions/Row/DefaultRow.opti-style.json
- src/cms/compositions/Row/RowHelper.ts
- src/cms/compositions/Section/DefaultSection.opti-style.json
- src/cms/compositions/Section/SectionHelper.ts
Added color consistency for Section/Row/Column and Fixed issue with Section bg-colors not working
> Added color consistency for Section/Row/Column.

- package.json
- src/cms/pages/ArticlePage/ArticlePage.astro
- src/styles/global.css
- yarn.lock
Should review everywhere set:html is used, determine if they should also leverage the typography plugin.
> Update Article display via Tailwind typography plugin

- src/graphql/queries/componentById.graphql
- src/graphql/queries/contentById.graphql
- src/graphql/queries/experience.graphql
- src/graphql/queries/pageById.graphql
- src/graphql/queries/siteSettingsById.dam.graphql
- src/graphql/queries/siteSettingsById.graphql
- src/graphql/queries/siteStylesById.graphql
@kunalshetye -- for review/testing. Probably shouldn't merge it in until the current SaaS deployment is complete.
> Preview for content variations

- src/cms/components/MenuItemComponent/MenuItem.opti-type.json
- src/cms/shared/Header.astro
- src/graphql/queries/siteSettingsByHostname.dam.graphql
- src/graphql/queries/siteSettingsByHostname.graphql
- src/graphql/queries/siteSettingsById.dam.graphql
- src/graphql/queries/siteSettingsById.graphql
> Add "LinkText" prop to menu item to help with display

- src/layouts/Layout.astro
Add a key to the body so we can target PERS and EXP using Optimizely Web and also for custom CSS
> Add content key to allow for EXP / PERS targeting

- src/cms/components/PageAdminSettingsComponent/PageAdminSettings.opti-type.json
Note: content pack to be updated in a future PR
> Make external preview setting localized

- src/cms/components/TextComponent/TextStyles.opti-style.json
- src/cms/components/TextComponent/TextStyling.ts
closes https://github.com/kunalshetye/opti-astro/issues/161
> added text styling options

- src/cms/compositions/Row/CardRow.opti-style.json
- src/cms/compositions/Row/CarouselRow.opti-style.json
- src/cms/compositions/Row/DefaultRow.opti-style.json
- src/cms/compositions/Row/RowHelper.ts
Fixes https://github.com/kunalshetye/opti-astro/issues/159
The following commands need to be executed:
```sh
yarn install
yarn styles:push
```
> Feature width on rows

- src/cms/components/ArticleListComponent/ArticleList.opti-type.json
- src/cms/components/ButtonComponent/Button.opti-type.json
- src/cms/components/CallToActionComponent/CallToAction.opti-type.json
- src/cms/components/CardComponent/Card.opti-type.json
- src/cms/components/CarouselComponent/Carousel.opti-type.json
- src/cms/components/CollapseComponent/Collapse.opti-type.json
- src/cms/components/DividerComponent/Divider.opti-type.json
- src/cms/components/GridComponent/Grid.opti-type.json
- src/cms/components/HeroComponent/Hero.opti-type.json
- src/cms/components/IframeComponent/Iframe.opti-type.json
- src/cms/components/ImageComponent/Image.opti-type.json
- src/cms/components/MenuItemComponent/MenuItem.opti-type.json
- src/cms/components/OdpFormComponent/OdpForm.opti-type.json
- src/cms/components/PageAdminSettingsComponent/PageAdminSettings.opti-type.json
- src/cms/components/PageSeoSettingsComponent/PageSeoSettings.opti-type.json
- src/cms/components/ParagraphComponent/Paragraph.opti-type.json
- src/cms/components/PlaceholderItemComponent/PlaceholderItem.opti-type.json
- src/cms/components/PlaceholdersConfigurationComponent/PlaceholdersConfiguration.opti-type.json
- src/cms/components/SiteSettingsComponent/SiteSettings.opti-type.json
- src/cms/components/SiteStylesComponent/SiteStyles.opti-type.json
- src/cms/components/TextComponent/Text.opti-type.json
- src/cms/components/VideoComponent/Video.opti-type.json
- src/cms/components/VideoExternalComponent/VideoExternal.opti-type.json
- src/cms/media/CssMedia/CssMedia.opti-type.json
- src/cms/pages/ArticlePage/ArticlePage.opti-type.json
- src/cms/pages/LandingPage/LandingPage.opti-type.json
- src/cms/pages/MockupPage/MockupPage.opti-type.json
@kunalshetye  this is ready to go, just held off on merging to make sure I didn't cause any conflicts with any changes you were in the process of making.
> Update description for content types
